apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: ServiceMeshConNA2020
spec:
  libPaths:
    - lib
  environments:
    default:
      defaultNamespace: jupyterhub
      server: https://kubernetes.docker.internal:6443
  vars:
    external:
      - default: disabled
        name: ISTIO
