FROM jupyterhub/k8s-hub:0.9.0
COPY spawner.py /usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py
COPY objects.py /usr/local/lib/python3.6/dist-packages/kubespawner/objects.py

# docker build -t jupyterhub/k8s-hub:0.9.0-patch .
